### ISSUE TITLE
Missing Example for creating Actors with Parameters

### ISSUE THREAD

**Issue by bjoernhaeuser** [scaldi/scaldi-akka#1]
Hi, 

I am just trying my first steps with akka + scaldi (inside play framework). The library looks awesome, thanks!

We are currently heavily using Actors with Parameters, but I am unable to see how to inject those.

This is my current actor definition:

``` scala
class OrderActor(orderUuid: String)(implicit inj: Injector) extends Actor with ActorLogging with AkkaInjectable {
```

Thanks in advance
Björn

**Comment by Jorik5702** [comment]
Instead of creating the actor with saladi, you can use scaldi to define the class to use of the actor. With this approach, you can create Props with constructor args as needed.

    bind[Class[_]] identifiedBy 'BusinessModuleClass to classOf[BusinessModule]

and

   val cl: Class[_] = inject[Class[_]]('BusinessModuleClass)
   val bmp = Props(cl, injector, 42)
   val firstBusinessModule = context.actorOf(bmp)
